spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/apms_mdm}
    username: ${DB_USERNAME:apms_mdm}
    password: ${DB_PASSWORD:change-me-local-only}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
